# Homework №1
## Задание

1. Создать **публичный** репозиторий на GitHub на основе шаблона `aie-student-template`:
   - зайти на страницу шаблона;
   - нажать кнопку «Use this template»;
   - выбрать создание нового репозитория в своём аккаунте;
   - задать осмысленное имя репозитория (по инструкции курса).
2. Убедиться, что репозиторий создан и доступен по публичной ссылке.

---

1. Клонировать созданный репозиторий к себе на компьютер.
2. Настроить Git, если ранее не настраивался (имя и e-mail пользователя).
3. Убедиться, что команды `git status` и `git log` работают и показывают состояние репозитория.

---

1. В корне репозитория создать папку `homeworks/`, если её ещё нет.
2. Внутри `homeworks/` создать папку `HW01/`.
3. В папке `homeworks/HW01/` создать файл `HW01.ipynb` с кодом по NumPy.

---

В файле `HW01.ipynb` должны быть:

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [6]:
# Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

In [7]:
# Создание массива из обычного списка
arr_from_list = np.array([1, 2, 3, 4])
print("Массив из списка: arr_from_list =", arr_from_list, end='\n\n')

# Создание массива нулей
zeros_arr = np.zeros(5)
print("Массив из пяти нулей: zeros_arr =", zeros_arr, end='\n\n')

# Создание массива единиц (двумерный, размером 2x3)
ones_arr = np.ones((2, 3))
print("Массив единиц 2x3: ones_arr\n", ones_arr, end='\n\n')

# Создание массива с помощью arange
range_arr = np.arange(0.0, 1.0, 0.1)  # от 0 до 1 с шагом 0.1
print("Массив через arange: range_arr =", range_arr, end='\n\n')

Массив из списка: arr_from_list = [1 2 3 4]

Массив из пяти нулей: zeros_arr = [0. 0. 0. 0. 0.]

Массив единиц 2x3: ones_arr
 [[1. 1. 1.]
 [1. 1. 1.]]

Массив через arange: range_arr = [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]



In [8]:
print("Массив единиц 2x3: ones_arr\n", ones_arr, end='\n\n')

# Выводим форму массива ones_arr: количество строк и столбцов
print("Размеры массива ones_arr:", ones_arr.shape)  # (2, 3) — 2 строки, 3 столбца

# Выводим тип данных элементов массива ones_arr
print("Тип данных элементов ones_arr:", ones_arr.dtype)    # int64 (или int32, зависит от системы)

Массив единиц 2x3: ones_arr
 [[1. 1. 1.]
 [1. 1. 1.]]

Размеры массива ones_arr: (2, 3)
Тип данных элементов ones_arr: float64


In [9]:
# Зададим одномерный массив
data = np.array([10, 20, 30, 40, 50])

# Получаем один элемент по индексу
print("Элемент с индексом 0:", data[0])               # 10
print("Элемент с индексом 2:", data[2], end='\n\n')   # 30

# Извлечение части массива — срез
print("Срез [1:4]:", data[1:4])   # [20, 30, 40] — элементы с 1 по 3

# Двумерный массив
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Получаем один элемент: строка 1, столбец 2
print("Элемент [1, 2]:", matrix[1, 2])     # 6

# Срез: первые две строки и первые два столбца
print("Подмассив [:2, :2]:\n", matrix[:2, :2])


Элемент с индексом 0: 10
Элемент с индексом 2: 30

Срез [1:4]: [20 30 40]
Элемент [1, 2]: 6
Подмассив [:2, :2]:
 [[1 2]
 [4 5]]


In [10]:
# Два массива одинакового размера
values = np.array([10, 15, 20, 25, 30, 15, 20])
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 9, 8, 7, 6])

print("a:", a)
print("b:", b, end='\n\n')
print("a + b:", a + b)
print("a * b:", a * b, end='\n\n')

print("values:", values, end='\n\n')

# Статистика
print("Минимум (min):", values.min())
print("Максимум (max):", values.max())
print("Сумма (sum):", values.sum())
print("Среднее (mean):", values.mean())

print("Дисперсия (var):", values.var())
print("Стандартное отклонение (std):", values.std())
print("Медиана (median):", np.median(values))

print("Сумма чётных чисел:", values[values % 2 == 0].sum())
print("Количество значений > 18:", (values > 18).sum())

a: [1 2 3 4 5]
b: [10  9  8  7  6]

a + b: [11 11 11 11 11]
a * b: [10 18 24 28 30]

values: [10 15 20 25 30 15 20]

Минимум (min): 10
Максимум (max): 30
Сумма (sum): 135
Среднее (mean): 19.285714285714285
Дисперсия (var): 38.77551020408163
Стандартное отклонение (std): 6.226998490772391
Медиана (median): 20.0
Сумма чётных чисел: 80
Количество значений > 18: 4
